---
name: CI

on: # yamllint disable-line rule:truthy
  push:
    branches: [main]
  pull_request:
    branches: [main]

concurrency:
  group: "${{ github.head_ref || github.ref }}-${{ github.workflow }}"
  cancel-in-progress: true

jobs:
  lint-test:
    name: Lint and Test
    runs-on: ubuntu-22.04
    # Add "id-token" with the required permissions.
    permissions:
      contents: "read"
      id-token: "write"
    steps:
      - uses: actions/checkout@v5

      # Authenticate with Google Cloud to acquire an access token
      - id: auth
        name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v3
        with:
          token_format: "access_token"
          workload_identity_provider: ${{ secrets.WIF_PROVIDER }}
          service_account: ${{ secrets.SERVICE_ACCOUNT }}

      # Authenticating with Dockerhub ensures image pulls are authenticated, so not as severely rate limited
      - name: Log in to Dockerhub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Also log docker in to GCP artifact registry, to allow image pulls from our private registries
      - name: Log in to Google Docker Artifact Registry
        uses: docker/login-action@v3
        with:
          registry: europe-west2-docker.pkg.dev
          username: oauth2accesstoken
          password: ${{ steps.auth.outputs.access_token }}

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version-file: .python-version
          cache: pipenv

      - name: Install Pipenv
        run: pipx install pipenv==2024.0.1

      - name: Install dependencies
        run: make install-dev

      - name: Lint Python
        run: make lint

      - name: Test
        run: make test

      - name: Docker Build
        run: make docker-build
